"""
Kubernetes + ACR Agent — Build, Push & Deploy with Error-Rectify-Rerun Loop
============================================================================
Responsibilities:
  1. ACR BUILD & PUSH  — Run `az acr build` to build the Docker image from the
                         repo-root Dockerfile and push it to Azure Container Registry.
  2. AKS CREDENTIALS   — Run `az aks get-credentials` to configure kubectl.
  3. K8S DEPLOY        — Apply Kubernetes manifests (from k8s/ directory, or
                         auto-generated by Gemini if none exist).
  4. HEALTH CHECK      — Wait for Deployments to reach Ready state.
  5. ERROR-RECTIFY-RERUN — On any `az` or `kubectl` error, send the error +
                         current manifests to Gemini for a corrected version,
                         write the fix, and retry — up to MAX_RETRIES times.

Usage:
  python k8s_acr_agent.py [--dry-run] [--skip-build] [--skip-deploy] [--max-retries N]

Environment variables (ai_agents/.env):
  GEMINI_API_KEY         — Google Gemini API key
  AZURE_SUBSCRIPTION_ID  — Target Azure subscription
  AZURE_TENANT_ID        — Azure tenant ID
  AZURE_CLIENT_ID        — Service Principal client ID
  AZURE_CLIENT_SECRET    — Service Principal client secret
  ACR_NAME               — ACR registry name (e.g. myacr)
  ACR_LOGIN_SERVER       — ACR login server (e.g. myacr.azurecr.io)
  AKS_CLUSTER_NAME       — AKS cluster name
  RESOURCE_GROUP         — Azure resource group containing AKS + ACR
  IMAGE_NAME             — Docker image name (e.g. myapp)
  IMAGE_TAG              — Docker image tag (default: latest)
  K8S_NAMESPACE          — Target Kubernetes namespace (default: default)
  K8S_MAX_RETRIES        — Max error-rectify cycles (default: 3)
"""

import os
import sys
import json
import time
import argparse
import subprocess
from pathlib import Path
from google import genai
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Bootstrap
# ---------------------------------------------------------------------------
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass

load_dotenv(dotenv_path=os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env'))

GEMINI_MODEL = "gemini-2.5-flash"
REPO_ROOT = Path(__file__).resolve().parent.parent.parent   # …/Azure-Landing-zone/
K8S_MANIFESTS_DIR = REPO_ROOT / "k8s"
DEFAULT_MAX_RETRIES = int(os.getenv("K8S_MAX_RETRIES", "3"))
HEALTH_POLL_INTERVAL = 15   # seconds
HEALTH_TIMEOUT = 300        # seconds to wait for pods to be Ready


def get_env(name: str, default: str = None, required: bool = False) -> str:
    val = os.getenv(name, default)
    if required and not val:
        print(f"[ERROR] Required environment variable '{name}' is not set.")
        sys.exit(1)
    return val


def get_gemini_client() -> genai.Client:
    return genai.Client(api_key=get_env("GEMINI_API_KEY", required=True))


# ---------------------------------------------------------------------------
# Subprocess helpers
# ---------------------------------------------------------------------------

def run_cmd(
    args: list[str],
    dry_run: bool = False,
    capture: bool = True,
    env_extra: dict = None,
) -> tuple[int, str, str]:
    """
    Run a shell command and return (returncode, stdout, stderr).
    Merges env_extra into the current environment if provided.
    """
    print(f"  [cmd] {' '.join(args)}")
    if dry_run:
        print("    [DRY RUN] Skipping.")
        return 0, "[DRY RUN]", ""

    env = os.environ.copy()
    if env_extra:
        env.update(env_extra)

    result = subprocess.run(args, capture_output=capture, text=True, env=env)
    if result.stdout:
        print(result.stdout[-3000:])
    if result.stderr:
        print(result.stderr[-2000:])
    return result.returncode, result.stdout, result.stderr


def az_login(dry_run: bool) -> bool:
    """Login to Azure using Service Principal credentials from env."""
    client_id = get_env("AZURE_CLIENT_ID")
    client_secret = get_env("AZURE_CLIENT_SECRET")
    tenant_id = get_env("AZURE_TENANT_ID")

    if not all([client_id, client_secret, tenant_id]):
        print("  [INFO] Azure SP credentials not set — assuming already logged in via az cli.")
        return True

    print("\n[K8s/ACR Agent] Logging in to Azure…")
    rc, _, _ = run_cmd(
        ["az", "login", "--service-principal",
         "--username", client_id,
         "--password", client_secret,
         "--tenant", tenant_id],
        dry_run=dry_run,
    )
    if rc != 0:
        print("  [ERROR] Azure login failed.")
        return False

    sub_id = get_env("AZURE_SUBSCRIPTION_ID")
    if sub_id:
        run_cmd(["az", "account", "set", "--subscription", sub_id], dry_run=dry_run)

    print("  ✓ Azure login successful.")
    return True


# ---------------------------------------------------------------------------
# PHASE 1 — ACR Build & Push
# ---------------------------------------------------------------------------

class AcrPhase:
    def __init__(
        self,
        dry_run: bool,
        client: genai.Client,
        max_retries: int,
        image_name: str = None,
        image_tag: str = None,
        build_context_dir: Path = None,
        acr_name: str = None,
        resource_group: str = None,
    ):
        self.dry_run = dry_run
        self.client = client
        self.max_retries = max_retries
        self.acr_name = acr_name or get_env("ACR_NAME", required=True)
        self.acr_login_server = get_env("ACR_LOGIN_SERVER")
        self.image_name = image_name or get_env("IMAGE_NAME", "app")
        self.image_tag = image_tag or get_env("IMAGE_TAG", "latest")
        self.resource_group = resource_group or get_env("RESOURCE_GROUP", required=True)
        self.build_context_dir = build_context_dir or REPO_ROOT

    @property
    def full_image_ref(self) -> str:
        server = self.acr_login_server or f"{self.acr_name}.azurecr.io"
        return f"{server}/{self.image_name}:{self.image_tag}"

    def _build_cmd(self) -> list[str]:
        return [
            "az", "acr", "build",
            "--registry", self.acr_name,
            "--image", f"{self.image_name}:{self.image_tag}",
            "--resource-group", self.resource_group,
            str(self.build_context_dir),   # Build context (app folder or repo root)
        ]

    def _ask_gemini_fix(self, error_output: str) -> dict | None:
        dockerfile_content = ""
        dockerfile_path = REPO_ROOT / "dockerfile"
        if not dockerfile_path.exists():
            dockerfile_path = REPO_ROOT / "Dockerfile"
        if dockerfile_path.exists():
            dockerfile_content = dockerfile_path.read_text(encoding='utf-8', errors='replace')

        prompt = f"""You are an Azure DevOps and Docker expert.
The `az acr build` command failed with the following error.
Diagnose the issue and provide corrected file content if any file changes are needed.

## ACR BUILD ERROR
{error_output}

## CURRENT DOCKERFILE
```dockerfile
{dockerfile_content}
```

## ACR CONFIGURATION
- Registry name: {self.acr_name}
- Image: {self.image_name}:{self.image_tag}
- Resource group: {self.resource_group}

Respond ONLY with a JSON block inside ```json ... ```:
```json
{{
  "diagnosis": "Root cause explanation",
  "corrections": [
    {{
      "file_path": "relative/path/from/repo/root/to/file",
      "corrected_content": "Full corrected file content"
    }}
  ],
  "az_command_override": []
}}
```
- If the az command itself needs different arguments, put the full corrected command list in `az_command_override`.
- If no changes are needed (transient error), set corrections to [] and az_command_override to [].
"""
        try:
            from llm_client import generate_text_with_retry
            raw = generate_text_with_retry(self.client, prompt)
            if "```json" in raw:
                json_str = raw.split("```json")[1].split("```")[0].strip()
            elif "```" in raw:
                json_str = raw.split("```")[1].split("```")[0].strip()
            else:
                json_str = raw
            return json.loads(json_str)
        except Exception as exc:
            print(f"  [ERROR] Gemini call failed: {exc}")
            return None

    def run(self) -> bool:
        print("\n" + "="*65)
        print("  PHASE 1 — ACR Build & Push")
        print("="*65)
        print(f"  Registry   : {self.acr_name}")
        print(f"  Image      : {self.full_image_ref}")
        print(f"  Build ctx  : {REPO_ROOT}")

        cmd = self._build_cmd()
        for attempt in range(1, self.max_retries + 1):
            print(f"\n{'─'*65}")
            print(f"  ACR Build Attempt {attempt}/{self.max_retries}")
            print(f"{'─'*65}")
            rc, stdout, stderr = run_cmd(cmd, dry_run=self.dry_run)

            if rc == 0:
                print(f"\n✅ ACR build & push SUCCEEDED! Image: {self.full_image_ref}")
                return True

            print(f"\n❌ ACR build FAILED (exit code {rc}).")
            error_text = f"STDOUT:\n{stdout[-2000:]}\n\nSTDERR:\n{stderr[-2000:]}"
            print("\n[K8s/ACR Agent] Consulting Gemini for ACR fix…")
            fix = self._ask_gemini_fix(error_text)

            if fix:
                print(f"  Diagnosis: {fix.get('diagnosis', '')[:300]}")
                for corr in fix.get("corrections", []):
                    rel = corr.get("file_path", "")
                    content = corr.get("corrected_content", "")
                    if not rel or not content:
                        continue
                    full = REPO_ROOT / rel
                    print(f"  Applying fix → {rel}")
                    if not self.dry_run:
                        full.parent.mkdir(parents=True, exist_ok=True)
                        full.write_text(content, encoding='utf-8')
                override = fix.get("az_command_override", [])
                if override:
                    cmd = override
                    print(f"  Using corrected az command: {' '.join(cmd)}")

        print(f"\n⛔ ACR build failed after {self.max_retries} attempts.")
        return False


# ---------------------------------------------------------------------------
# PHASE 2 — AKS Credentials
# ---------------------------------------------------------------------------

def get_aks_credentials(dry_run: bool) -> bool:
    cluster = get_env("AKS_CLUSTER_NAME", required=True)
    rg = get_env("RESOURCE_GROUP", required=True)
    print("\n" + "="*65)
    print("  PHASE 2 — Get AKS Credentials")
    print("="*65)
    print(f"  Cluster: {cluster}  |  RG: {rg}")

    rc, _, stderr = run_cmd(
        ["az", "aks", "get-credentials",
         "--resource-group", rg,
         "--name", cluster,
         "--overwrite-existing"],
        dry_run=dry_run,
    )
    if rc != 0:
        print(f"  [ERROR] Could not get AKS credentials: {stderr}")
        return False
    print("  ✓ kubectl configured for cluster.")
    return True


# ---------------------------------------------------------------------------
# PHASE 3 — Generate or validate K8s manifests
# ---------------------------------------------------------------------------

DEFAULT_MANIFEST_TEMPLATE = """\
# Auto-generated by k8s_acr_agent — review before using in production
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {image_name}
  namespace: {namespace}
  labels:
    app: {image_name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {image_name}
  template:
    metadata:
      labels:
        app: {image_name}
    spec:
      containers:
        - name: {image_name}
          image: {full_image_ref}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {image_name}-service
  namespace: {namespace}
spec:
  type: LoadBalancer
  selector:
    app: {image_name}
  ports:
    - port: 80
      targetPort: 80
"""


def ensure_manifests(
    image_name: str,
    full_image_ref: str,
    namespace: str,
    client: genai.Client,
    dry_run: bool,
) -> list[Path]:
    """
    Return list of manifest files to apply.
    If k8s/ directory doesn't exist or is empty, generate a default manifest via Gemini.
    """
    print("\n" + "="*65)
    print("  PHASE 3 — Kubernetes Manifests")
    print("="*65)

    manifest_files = []
    if K8S_MANIFESTS_DIR.exists():
        manifest_files = sorted(K8S_MANIFESTS_DIR.glob("*.yaml")) + \
                         sorted(K8S_MANIFESTS_DIR.glob("*.yml"))

    if manifest_files:
        print(f"  Found {len(manifest_files)} manifest file(s) in {K8S_MANIFESTS_DIR}")
        return manifest_files

    # No manifests found — generate via Gemini or use template
    print("  No manifests found. Generating defaults with Gemini…")
    prompt = f"""You are a Kubernetes expert specialising in Azure AKS deployments.
Generate a production-ready Kubernetes Deployment and Service manifest for the following:

- Image: {full_image_ref}
- Application name: {image_name}
- Namespace: {namespace}
- Cloud: Azure AKS
- Best practices: resource limits, liveness/readiness probes, Labels, imagePullPolicy: Always

Return ONLY a valid YAML inside a ```yaml block. Combine all resources with --- separators.
"""
    try:
        from llm_client import generate_text_with_retry
        raw = generate_text_with_retry(client, prompt)
        if "```yaml" in raw:
            yaml_content = raw.split("```yaml")[1].split("```")[0].strip()
        elif "```" in raw:
            yaml_content = raw.split("```")[1].split("```")[0].strip()
        else:
            yaml_content = raw
    except Exception as exc:
        print(f"  [WARN] Gemini manifest generation failed ({exc}). Using built-in template.")
        yaml_content = DEFAULT_MANIFEST_TEMPLATE.format(
            image_name=image_name,
            namespace=namespace,
            full_image_ref=full_image_ref,
        )

    # Write generated manifest
    K8S_MANIFESTS_DIR.mkdir(parents=True, exist_ok=True)
    manifest_path = K8S_MANIFESTS_DIR / "deployment.yaml"
    print(f"  Writing generated manifest → {manifest_path.relative_to(REPO_ROOT)}")
    if not dry_run:
        manifest_path.write_text(yaml_content, encoding='utf-8')
    return [manifest_path]


# ---------------------------------------------------------------------------
# PHASE 4 — Apply manifests + health check
# ---------------------------------------------------------------------------

class K8sDeployPhase:
    def __init__(
        self,
        manifest_files: list[Path],
        namespace: str,
        image_name: str,
        full_image_ref: str,
        dry_run: bool,
        client: genai.Client,
        max_retries: int,
    ):
        self.manifest_files = manifest_files
        self.namespace = namespace
        self.image_name = image_name
        self.full_image_ref = full_image_ref
        self.dry_run = dry_run
        self.client = client
        self.max_retries = max_retries

    def _apply_manifests(self) -> tuple[int, str, str]:
        """Run kubectl apply for all manifest files."""
        for mf in self.manifest_files:
            rc, stdout, stderr = run_cmd(
                ["kubectl", "apply", "-f", str(mf), "-n", self.namespace],
                dry_run=self.dry_run,
            )
            if rc != 0:
                return rc, stdout, stderr
        return 0, "All manifests applied.", ""

    def _wait_for_ready(self) -> bool:
        """Poll until Deployment rollout is complete or timeout."""
        print(f"\n  Waiting for Deployment '{self.image_name}' to become Ready…")
        elapsed = 0
        while elapsed < HEALTH_TIMEOUT:
            rc, stdout, _ = run_cmd(
                ["kubectl", "rollout", "status",
                 f"deployment/{self.image_name}",
                 "-n", self.namespace,
                 "--timeout=30s"],
                dry_run=self.dry_run,
            )
            if rc == 0:
                print("  ✓ Deployment is Ready!")
                return True
            time.sleep(HEALTH_POLL_INTERVAL)
            elapsed += HEALTH_POLL_INTERVAL
            print(f"  [{elapsed}s] Still waiting…")
        print("  [WARN] Timed out waiting for Deployment to become Ready.")
        return False

    def _get_pod_events(self) -> str:
        """Collect recent events and pod status for debugging."""
        _, events, _ = run_cmd(
            ["kubectl", "get", "events", "-n", self.namespace,
             "--sort-by=.metadata.creationTimestamp", "--field-selector",
             f"involvedObject.name={self.image_name}"],
            dry_run=self.dry_run,
        )
        _, pods, _ = run_cmd(
            ["kubectl", "get", "pods", "-n", self.namespace,
             "-l", f"app={self.image_name}", "-o", "wide"],
            dry_run=self.dry_run,
        )
        _, describe, _ = run_cmd(
            ["kubectl", "describe", "deployment", self.image_name,
             "-n", self.namespace],
            dry_run=self.dry_run,
        )
        return f"EVENTS:\n{events}\n\nPODS:\n{pods}\n\nDESCRIBE:\n{describe}"

    def _ask_gemini_fix(self, error_output: str) -> dict | None:
        """Send error context to Gemini for manifest corrections."""
        manifest_content = ""
        for mf in self.manifest_files:
            try:
                manifest_content += f"\n--- {mf.name} ---\n{mf.read_text(encoding='utf-8')}\n"
            except Exception:
                pass

        prompt = f"""You are a Kubernetes and Azure AKS expert.
A Kubernetes deployment failed. Diagnose the issue and provide corrected manifest files.

## ERROR OUTPUT
{error_output}

## CURRENT MANIFESTS
{manifest_content}

## DEPLOYMENT CONTEXT
- Image: {self.full_image_ref}
- Namespace: {self.namespace}
- Application: {self.image_name}

Respond ONLY with a JSON block inside ```json ... ```:
```json
{{
  "diagnosis": "Root cause explanation",
  "corrections": [
    {{
      "file_path": "k8s/filename.yaml",
      "corrected_content": "Full corrected YAML content"
    }}
  ]
}}
```
- file_path is relative to the repository root.
- corrected_content is the COMPLETE file content.
- If the issue is transient (e.g. image pull backoff that just needs time), set corrections to [].
"""
        try:
            from llm_client import generate_text_with_retry
            raw = generate_text_with_retry(self.client, prompt)
            if "```json" in raw:
                json_str = raw.split("```json")[1].split("```")[0].strip()
            elif "```" in raw:
                json_str = raw.split("```")[1].split("```")[0].strip()
            else:
                json_str = raw
            return json.loads(json_str)
        except Exception as exc:
            print(f"  [ERROR] Gemini call failed: {exc}")
            return None

    def run(self) -> bool:
        print("\n" + "="*65)
        print("  PHASE 4 — Kubernetes Deploy")
        print("="*65)
        print(f"  Namespace  : {self.namespace}")
        print(f"  Manifests  : {[str(m.name) for m in self.manifest_files]}")

        # Ensure namespace exists
        run_cmd(
            ["kubectl", "create", "namespace", self.namespace,
             "--dry-run=client", "-o", "yaml"],
            dry_run=self.dry_run,
        )
        run_cmd(
            ["kubectl", "apply", "-f", "-"],
            dry_run=self.dry_run,
        )

        # Create namespace idempotently
        run_cmd(
            ["kubectl", "get", "namespace", self.namespace],
            dry_run=self.dry_run,
        )

        for attempt in range(1, self.max_retries + 1):
            print(f"\n{'─'*65}")
            print(f"  K8s Deploy Attempt {attempt}/{self.max_retries}")
            print(f"{'─'*65}")

            # Apply manifests
            rc, stdout, stderr = self._apply_manifests()
            if rc != 0:
                error_text = f"kubectl apply FAILED\nSTDOUT:\n{stdout}\nSTDERR:\n{stderr}"
                print(f"\n❌ {error_text[:500]}")
                fix = self._ask_gemini_fix(error_text)
                if fix:
                    self._apply_corrections(fix.get("corrections", []))
                continue

            # Wait for rollout
            ready = self._wait_for_ready()
            if ready:
                print("\n✅ Kubernetes deployment COMPLETE!")
                self._print_endpoint()
                return True

            # Rollout not ready — collect events and ask Gemini
            print("\n❌ Deployment did not become Ready in time.")
            events = self._get_pod_events()
            fix = self._ask_gemini_fix(events)
            if fix:
                print(f"  Diagnosis: {fix.get('diagnosis', '')[:300]}")
                self._apply_corrections(fix.get("corrections", []))

        print(f"\n⛔ K8s deploy failed after {self.max_retries} attempts.")
        return False

    def _apply_corrections(self, corrections: list[dict]):
        for corr in corrections:
            rel = corr.get("file_path", "").strip()
            content = corr.get("corrected_content", "")
            if not rel or not content:
                continue
            full = REPO_ROOT / rel
            print(f"  Applying manifest fix → {rel}")
            if not self.dry_run:
                full.parent.mkdir(parents=True, exist_ok=True)
                full.write_text(content, encoding='utf-8')
            # Refresh manifest file list if the file was updated
            for i, mf in enumerate(self.manifest_files):
                if mf.name == full.name:
                    self.manifest_files[i] = full

    def _print_endpoint(self):
        """Print the external IP / hostname of the LoadBalancer service."""
        print("\n  Fetching service endpoint…")
        for _ in range(10):
            rc, stdout, _ = run_cmd(
                ["kubectl", "get", "svc", f"{self.image_name}-service",
                 "-n", self.namespace,
                 "-o", "jsonpath={.status.loadBalancer.ingress[0].ip}"],
                dry_run=self.dry_run,
            )
            ip = stdout.strip()
            if ip and ip != "[DRY RUN]":
                print(f"\n  🌐 Application endpoint: http://{ip}")
                return
            time.sleep(10)
        print("  [INFO] External IP not yet assigned — check `kubectl get svc` later.")


class K8sAcrAgent:
    """
    Programmatic interface for the Orchestrator and external tools.
    """

    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run
        self.client = get_gemini_client()

    def run(self, args: dict = None) -> bool:
        args = args or {}
        dry_run = args.get("dry_run", self.dry_run)
        max_retries = int(args.get("max_retries", DEFAULT_MAX_RETRIES))
        skip_build = args.get("skip_build", False)
        skip_deploy = args.get("skip_deploy", False)

        namespace = args.get("namespace") or get_env("K8S_NAMESPACE", "default")
        image_name = args.get("image_name") or get_env("IMAGE_NAME", "app")
        image_tag = args.get("image_tag") or get_env("IMAGE_TAG", "latest")
        acr_name = args.get("acr_name") or get_env("ACR_NAME", required=True)
        acr_login_server = args.get("acr_login_server") or get_env("ACR_LOGIN_SERVER") or f"{acr_name}.azurecr.io"
        full_image_ref = f"{acr_login_server}/{image_name}:{image_tag}"
        
        build_context_dir = Path(args["build_context_dir"]) if args.get("build_context_dir") else (
            Path(args["app_dir"]) if args.get("app_dir") else REPO_ROOT
        )

        print("=" * 65)
        print("  K8s + ACR Agent — Build, Push & Deploy")
        print(f"  ACR Name  : {acr_name}")
        print(f"  Image     : {full_image_ref}")
        print(f"  Build Dir : {build_context_dir}")
        print(f"  AKS       : {get_env('AKS_CLUSTER_NAME', 'N/A')}")
        print(f"  Namespace : {namespace}")
        print(f"  Dry Run   : {dry_run}")
        print(f"  MaxRetries: {max_retries}")
        print("=" * 65)

        # Azure login
        if not az_login(dry_run):
            return False

        # Phase 1 — ACR Build & Push
        if not skip_build:
            acr_phase = AcrPhase(
                dry_run=dry_run,
                client=self.client,
                max_retries=max_retries,
                image_name=image_name,
                image_tag=image_tag,
                build_context_dir=build_context_dir,
                acr_name=acr_name,
            )
            success = acr_phase.run()
            if not success and not dry_run:
                print("\n[FATAL] ACR build failed. Cannot deploy without a valid image.")
                return False

        if skip_deploy:
            print("\n[INFO] --skip-deploy flag set. Skipping Kubernetes deployment.")
            print("[K8s/ACR Agent] Done.")
            return True

        # Phase 2 — AKS Credentials
        if not get_aks_credentials(dry_run):
            return False

        # Phase 3 — Manifests
        manifest_files = ensure_manifests(
            image_name=image_name,
            full_image_ref=full_image_ref,
            namespace=namespace,
            client=self.client,
            dry_run=dry_run,
        )

        # Phase 4 — Deploy + Error-Rectify-Rerun
        k8s_phase = K8sDeployPhase(
            manifest_files=manifest_files,
            namespace=namespace,
            image_name=image_name,
            full_image_ref=full_image_ref,
            dry_run=dry_run,
            client=self.client,
            max_retries=max_retries,
        )
        success = k8s_phase.run()
        print("\n[K8s/ACR Agent] Done.")
        return success


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="K8s + ACR Agent — Build, Push, Deploy & Auto-Fix"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Simulate all actions without running az/kubectl commands or writing files"
    )
    parser.add_argument(
        "--skip-build", action="store_true",
        help="Skip ACR build & push (assume image already exists)"
    )
    parser.add_argument(
        "--skip-deploy", action="store_true",
        help="Skip Kubernetes deployment (only build & push to ACR)"
    )
    parser.add_argument(
        "--image-name", default=None,
        help="Target container image name (overrides .env)"
    )
    parser.add_argument(
        "--image-tag", default=None,
        help="Target container image tag (overrides .env)"
    )
    parser.add_argument(
        "--build-dir", default=None,
        help="Custom build context directory containing Dockerfile"
    )
    parser.add_argument(
        "--namespace", default=None,
        help="Kubernetes namespace (default: default)"
    )
    parser.add_argument(
        "--max-retries", type=int, default=DEFAULT_MAX_RETRIES,
        help=f"Max error-rectify-rerun cycles (default: {DEFAULT_MAX_RETRIES})"
    )
    args = parser.parse_args()

    agent = K8sAcrAgent(dry_run=args.dry_run)
    success = agent.run({
        "dry_run": args.dry_run,
        "skip_build": args.skip_build,
        "skip_deploy": args.skip_deploy,
        "image_name": args.image_name,
        "image_tag": args.image_tag,
        "build_context_dir": args.build_dir,
        "namespace": args.namespace,
        "max_retries": args.max_retries,
    })
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()

